### ISSUE TITLE
Some Notifications Never Land in the Notification Area

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-notifications#50] opened 2018-09-13 05:40 UTC
_From @amxmln on July 24, 2018 7:21_

In Juno Beta 1, some notifications, namely AppCenter Update notifications and Telegram (with notifications set to "native") don't end up in the notification center despite the option being active in the Notification settings.

In GNOME Shell, Telegram's native notifications are kept in the notification area, so unless GNOME is handling them in a special way, I don't think they're meant to disappear.

**Comment by cassidyjames** [comment] 2018-09-13 05:40
@amxmln there was an issue where notifications weren't always being persisted due to a recent performance optimization—are you still seeing this on a fully updated Juno install? AppCenter notifications appear to work correctly now, but I'm not sure about Telegram.

**Comment by cassidyjames** [comment] 2018-09-13 05:41
(If this is fixed, it was likely a duplicate of #48)

**Comment by donadigo** [comment] 2018-09-13 07:51
@cassidyjames It might be just a side effect that we earlier removed handling for apps that were not sending app ID (which I'm still not agreeing with), we have the libraries like libbamf which are still available and work in Juno. If it's a recent issue, I guess that we will have to investigate this further.

**Comment by amxmln** [comment] 2018-09-13 08:51
Seems like Telegram’s notifications now show up in the notification centre correctly, however, clicking on them does nothing.

I presume they are filed under "Other" because of Telegram not sending an ID or something?

**Comment by lenemter** [comment] 2023-06-17 16:55
Closing since the issue is old and not reproducible anymore.

**Closed by lenemter** 2023-06-17 16:55 UTC
Labels: Status: Incomplete
