### ISSUE TITLE
Clear All Notifications button can't be clicked

### ISSUE THREAD

**Issue by rodolfoggp** [elementary/wingpanel-indicator-notifications#75] opened 2019-08-09 18:38 UTC
When there are some notifications on the screen, I can't click on the Clear All Notifications button (because they appear on top of this button).

**Comment by Speedy-Gonzalez** [comment] 2020-04-02 18:43
Does this problem still exist? I have installed eOS 5.1 Hera and it works fine for me. The button is always visible and performs the desired function.

**Comment by pshone** [comment] 2020-06-18 18:26
I am still experiencing it in Hera 5.1.5.  The pop up notifications are in front of the menu option not allowing you to click "clear all".  You have to first clear all the pop up notifications then you can access the "clear all"

**Comment by ryonakano** [comment] 2020-06-18 20:47
Closing as a duplicate of #64

**Closed by ryonakano** 2020-06-18 20:47 UTC
