### ISSUE TITLE
Notifications Showing in right-mid screen 

### ISSUE THREAD

**Issue by MichaelToniolo** [elementary/wingpanel-indicator-notifications#273] opened 2023-10-20 12:44 UTC
### What Happened?

Hello everyone!!

I'm using eOS 7.1 version today on my laptop. I have noticed when some notification shows up the notification bubble goes to the right-mid screen, basically the notification slide up-to-down to the mid center.
This happened with anyone notification(Volume, Screen light, copy folder and others)
![aptupdate](https://github.com/elementary/wingpanel-indicator-notifications/assets/37878223/8ba1f06f-1690-4a41-a037-c8ef41f04dc2)
![flameshotnotification](https://github.com/elementary/wingpanel-indicator-notifications/assets/37878223/5d6f4cd3-cc0a-48a4-b06d-c8ff137a23f9)
![volumenotification](https://github.com/elementary/wingpanel-indicator-notifications/assets/37878223/620a4465-6b68-4e0a-9ae5-cd2a74496117)

### Steps to Reproduce

Any Notification
Shows Up

### Expected Behavior

The notification needs to show above wingpanel on right-side floating

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Dual-Core Intel® Core(TM) i5-7200U CPU @ 2.50GHz
Intel® HD Graphics 620
12 GB memory
1 TB storage (NVMe SSD)
Laptop Acer (1366x768)

**Comment by danirabbit** [comment] 2023-10-20 16:35
Hey thanks for your issue report! This issue has already been reported, so I'm closing this one as a duplicate of https://github.com/elementary/notifications/issues/218

**Closed by danirabbit** 2023-10-20 16:35 UTC
