### ISSUE TITLE
no tray icons

### ISSUE THREAD

**Issue by Jeansen** [elementary/wingpanel-indicator-notifications#57] opened 2018-11-11 18:30 UTC
When I upgraded from Loki to Juno I recognized that there were no tray icons any longer. I could work around this by doing

```
cp /etc/xdg/autostart/indicator-application.desktop ~/.config/autostart/
sed -i '/OnlyShowIn/d' ~/.config/autostart/indicator-application.desktop
```

After that my tray icons showed up again and everything was fine.

But with the last update to 2.1.2 it does not work any longer. 

I'd appreciate any hints to get it working again because tray icons are simply one thing I do not want to miss.

BTW: I've documented everything I did here: https://jeansen.github.io/2018/10/19/upgrade-elementaryos-loki-to-juno.html

**Comment by peteruithoven** [comment] 2018-11-11 18:44
Thanks for the report! This is actually a duplicate of https://github.com/elementary/wingpanel/issues/96

**Closed by peteruithoven** 2018-11-11 18:44 UTC
Labels: Status: Duplicate

**Comment by peteruithoven** [comment] 2018-11-11 19:13
@Jeansen You're sharing false information on your blog. If you look at the following project you'll notice that it's more than updating the sources. 
https://github.com/orgs/elementary/projects/20
You'll be much better of using a tool like Aptik. (don't backup the dconf database)

**Comment by Jeansen** [comment] 2018-11-12 10:30
@peteruithoven Thank your for taking the time reading the article and your feedback. I'll correct/remove the post accordingly (Don't want to spread false information, after all). :smile:
