### ISSUE TITLE
Pop-up notifications persist on screen when cursor hovers over the notification

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/wingpanel-indicator-notifications#98] opened 2020-01-27 18:40 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Pop-up notifications persist on the screen when the mouse cursor hovers over them, they do not minimize and automatically go into the notifications bar. 

### To Reproduce
Happens only occasionally, no known way to reproduce.

### Expected behavior
The pop-up should close after x number of seconds (I think it is set to 1s by default) and go into the notifications bar (the bell icon).

## Platform Information
 - elementary OS 5.1 Hera
 - Dell XPS 13 9380 Dual Booted

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
If there is a feature to disable that i.e even if the cursor hovers over the notification, the pop-up closes after x number of seconds, that would be great.

**Comment by danrabbit** [comment] 2020-02-14 00:47
Notifications remaining on screen while hovered is the intended behavior. Closing as "Design conflict"

**Closed by danrabbit** 2020-02-14 00:47 UTC

**Comment by janxkoci** [comment] 2020-02-24 21:19
@danrabbit I think you misunderstood.

The issue is that _sometimes_ when you hover over a notification it gets stuck even if you mouse away from it. It shows the **x** in the corner, but my mouse is already away doing other stuff. I have to hover over it again to make it go away (or click the **x**).

And in some rare cases this _stuck state_ happens even without me interacting with the notification bubble at al. I noticed this e.g. after login from suspend or lockscreen. There is a notification bubble stuck in the corner with **x**, while my cursor is somewhere else.

One more detail: I noticed it mostly happens with system icons - sound volume, screen brightness, or wifi disconnected (this is the one I see after login _every time_, but gets stuck only sometimes).
