### ISSUE TITLE
Black screen after receive notification in a second screen

### ISSUE THREAD

**Issue by charly-palencia** [elementary/wingpanel-indicator-notifications#238] opened 2022-02-02 23:11 UTC
### What Happened?

I've been struggling with an issue with notifications and multiple workspaces, the screen is turning blank and it some cases it logs out. It's happening in different laptops in my company. 

VIDEO 
https://youtu.be/lTeb1tTbFI4
 
**Actual Behavior**
- The screen turns black and then all the app has a odd sizes
- Some time it just log out the user
Check the video with the example,

### Steps to Reproduce

- Go to main workspace and open some app with active notification
- then, open a new app and send it to a second workspace
- Click the bell icon (notification icon) in the status bar and clear all the notification
- When receive the message bubble , click it and it should be move to the main workspace.
- Now, go back to the second workspace, and receive a new bubble notification.

### Expected Behavior

I should received the notification or click it without any black screen or any error 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

laptop                      
    description: Notebook
    product: ROG Zephyrus G14 GA401QC_GA401QC
    vendor: ASUSTeK COMPUTER INC.
    version: 1.0
    serial: M6NRKD01025522C
    width: 64 bits
    capabilities: smbios-3.3.0 dmi-3.3.0 smp vsyscall32
    configuration: boot=normal chassis=notebook family=ROG Zephyrus G14 uuid=F2C81A40-AB06-41E5-8032-8E1B6874D7BF
  *-core
       description: Motherboard
       product: GA401QC
       vendor: ASUSTeK COMPUTER INC.
       physical id: 0
       version: 1.0
       serial: H516MC00BT
       slot: MIDDLE
     *-firmware
          description: BIOS
          vendor: American Megatrends International, LLC.
          physical id: 0
          version: GA401QC.406
          date: 05/13/2021
          size: 64KiB
          capacity: 16MiB
          capabilities: pci upgrade shadowing cdboot bootselect socketedrom edd acpi smartbattery biosbootspecification uefi
     *-memory
          description: System Memory
          physical id: 13
          slot: System board or motherboard
          size: 16GiB

**Comment by lenemter** [comment] 2023-09-09 07:07
Closing as duplicate of https://github.com/elementary/notifications/issues/139 which has been fixed in OS 7.

**Closed by lenemter** 2023-09-09 07:07 UTC
