### ISSUE TITLE
Notifications don't render escaped html correctly

### ISSUE THREAD

**Issue by AndrewVos** [elementary/wingpanel-indicator-notifications#62] opened 2019-01-16 14:44 UTC
Some apps (and I say some, but I only know of one) pass encoded html through to notify-send. I'm not sure if plank should be supporting this, stripping it out, or just not caring.

It seems like stripping it out would be a good first step?

![image](https://user-images.githubusercontent.com/363618/51256308-02db5800-199d-11e9-99a0-310e0631a834.png)

**Comment by tintou** [comment] 2019-01-16 14:50
duplicate of #58

**Closed by tintou** 2019-01-16 14:50 UTC

**Comment by AndrewVos** [comment] 2019-01-16 14:52
@tintou :( I was going to try work on this for my first contribution.

Thanks anyway!
