### ISSUE TITLE
Update/Restart don't get updated after action

### ISSUE THREAD

**Issue by alex285** [elementary/wingpanel-indicator-notifications#118] opened 2020-06-25 21:16 UTC
## Describe the bug
When we get updates we get a notification "You have updates"; In this case I updated from Terminal so I'm not sure if the notification would be gone if I had used AppCenter;

Then, after I installed the updates I got a new notification for "Reboot", I guess because I had some new kernel installations; I again reboot from terminal, but on the next boot I still see the two Notifications about Updates and Reboot, that aside they should have gone, they are also confusing?? Did I actually reboot? I rebooted again to make sure :p ..this time from UI, and the notifications are still there; tested on QEMU, on elementary 6.0 daily builds; 

![restart-bug](https://user-images.githubusercontent.com/11244308/85796092-05211480-b742-11ea-8e70-696dbf04a582.png)

**Comment by danirabbit** [comment] 2023-08-30 18:38
Closing as a duplicate of #204

**Closed by danirabbit** 2023-08-30 18:38 UTC
