### ISSUE TITLE
Calendar notifications are listed as "Other" section instead of "Calendar"

### ISSUE THREAD

**Issue by andirsun** [elementary/wingpanel-indicator-notifications#209] opened 2021-06-30 13:44 UTC
## What Happened

![Screenshot from 2021-06-30 08-34-43](https://user-images.githubusercontent.com/22928302/123970982-3fd61200-d97f-11eb-80e4-b8fa06b84aac.png)

**Comment by danrabbit** [comment] 2021-06-30 17:18
I'm going to close this is a duplicate of https://github.com/elementary/calendar/issues/677 since the fix is the same: the calendar daemon needs a desktop file in the correct path

**Closed by danrabbit** 2021-06-30 17:18 UTC
