### ISSUE TITLE
Notification List Covers Notification Dropdown

### ISSUE THREAD

**Issue by jalcine** [elementary/wingpanel-indicator-notifications#184] opened 2021-02-19 18:13 UTC
## What Happened
I tend to leave my laptop locked and powered over night. I woke up and came to my desk to find a huge list of the same notification over and over. After closing about 10 of these notifications, I tried to open the panel to see if I could do it en-masse.

## Expected Behavior
Clicking the bell with the red dot should have allowed me to clear out all of the notifications _and_ it should have perhaps have a higher "z-index" than that of the actual notifications.

## Steps to Reproduce
![Screenshot from 2021-02-19 10-08-57](https://user-images.githubusercontent.com/452100/108544144-e6f0c180-729a-11eb-8450-9cacf0c30c58.png)

1. Generate about +60 notifications.
2. Lock the screen
3. Return to unlocked screen.

## Platform Information
* elementary OS 5.1.7 Hera
* Built on Ubuntu 18.04.4 LTS
* Linux 5.4.0-65-generic
* GTK 3.22.30

**Comment by stayinside4ever** [comment] 2021-05-18 07:19
Still a problem 2 years later (elementary OS 5.1.7 Hera, Built on Ubuntu 18.04.4 LTS, Linux 5.4.0-73-generic, GTK 3.22.30)... Especially annoying because, when I don't turn my computer on for a while, tens of notifications tend to accumulate and cover up a solid fifth of my screen for a bit after logon.

**Comment by lenemter** [comment] 2023-09-09 07:15
Closing as duplicate of https://github.com/elementary/gala/issues/91.

**Closed by lenemter** 2023-09-09 07:15 UTC
