### ISSUE TITLE
Special Notification Settings for Spotify and Other Music client.

### ISSUE THREAD

**Issue by Fatih20** [elementary/wingpanel-indicator-notifications#77] opened 2019-08-25 07:48 UTC
Currently, notification from spotify are labeled under "other". They should be labeled spotfiy instead. Furthermore, notification from spotify should also has its own settings like the built-in apps.

**Comment by danrabbit** [comment] 2019-08-25 15:11
This is because Spotify does not correctly identify itself to the notifications server and we have no way of knowing that these notifications are coming from Spotify.

This is a bug in Spotify and cannot be solved here. Closing as “Out if Scope”

**Closed by danrabbit** 2019-08-25 15:11 UTC

**Comment by Fatih20** [comment] 2019-08-25 15:21
Huh, I guess it's not possible to use mpris-player used for the "sound" thingy at wingpanel to identify the notification as coming from spotify? Not asking much, but hey, might be an interesting challenge for someone out there.

**Comment by janxkoci** [comment] 2020-02-24 21:32
The problem is that MPRIS and notification server are two separate technologies - and Spotify supports MPRIS, but doesn't support the notifications server properly.

You can try to ask Spotify about it here: https://community.spotify.com/t5/Desktop-Linux/bd-p/desktop_linux
