### ISSUE TITLE
gmail notifications don't remain in the Notification Center

### ISSUE THREAD

**Issue by rwoolf** [elementary/wingpanel-indicator-notifications#113] opened 2020-05-14 18:05 UTC
I have the Chrome browser installed.  I have gmail configured to provide notifications (and given Chrome permission to do so).  When mail arrives, a notification bubble does appear, and the EOS bell gets a red dot on it.  But as soon as the bubble goes away, the dot disappears on the bell, and nothing remains in the Notification Center.  In EOS notification settings "Other" is set to show missed items in the Notification Center.  Other apps that use "Other" such as Slack appropriately leave the notification in the Notification Center.  It would be good if notifications from gmail could remain in the Notification Center.

I am using:
![image](https://user-images.githubusercontent.com/15988007/81969314-fb50b100-95da-11ea-95b4-621e05bf6f87.png)

**Comment by cassidyjames** [comment] 2020-05-14 18:07
Do other Chrome notifications disappear in the same way? It's possible Chrome is actively withdrawing the notification, in which case there's nothing we can do from the OS-side.

**Comment by rwoolf** [comment] 2020-05-14 18:14
I don't know.  This is the first I have used notifications from Chrome and I'm not sure what other notifications it might provide.

This got me curious, however, and I tried using gmail from FireFox and gave FF permission to send notifications.  The notifications remain in the notification center, so you may be correct in that it is Chrome causing the problem.

**Comment by lenemter** [comment] 2023-06-17 16:53
Closing because I can't reproduce the issue.

**Closed by lenemter** 2023-06-17 16:53 UTC
Labels: Status: Incomplete
