### ISSUE TITLE
Notifications don't overlay on top of (some?) fullscreen apps

### ISSUE THREAD

**Issue by uncertainquark** [elementary/wingpanel-indicator-notifications#65] opened 2019-05-14 14:20 UTC
I miss notifications in certain fullscreen apps like MPV, because the notification doesn't overlay on them. I would think that crucial notifications like "Battery is low" would take priority over any fullscreen apps. Is this by design or some apps' specific?

**Comment by peteruithoven** [comment] 2019-05-14 14:48
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/134

**Closed by peteruithoven** 2019-05-14 14:48 UTC
