### ISSUE TITLE
Consider Enable Do Not Disturb temporarily

### ISSUE THREAD

**Issue by andirsun** [elementary/wingpanel-indicator-notifications#167] opened 2020-11-03 22:42 UTC
## Problem

Example : When I active DND for a meeting propuses (1 o 2 hours), then I forget turn Off again and I miss several notifications from all apps like slack etc. 
 
## Proposal

Like in the phones (Android, IOS), would be useful If elementary had the option to active DND only for 1~ 2 hours or undefined as current behavior. 

## Prior Art

![dnd-3dtouch_0](https://user-images.githubusercontent.com/22928302/98048205-3d74e580-1dfb-11eb-8720-9d1ba3d12492.jpg)

**Comment by danrabbit** [comment] 2020-11-03 22:45
Closing as a duplicate of https://github.com/elementary/settings-daemon/issues/11

**Closed by danrabbit** 2020-11-03 22:45 UTC
