### ISSUE TITLE
Click on missed notification doesn't open corresponding application

### ISSUE THREAD

**Issue by shantanu-csedu** [elementary/wingpanel-indicator-notifications#181] opened 2021-02-15 19:53 UTC
**How to regenerate:**
- Start any operation in terminal (sudo apt update)
- A notification will post when the operation ends
- Wait until notification dismiss (goes to missed notification list)
- Click on the missed notification

**Current behavior:**
Nothing happens 

**Expected behavior:**
Should open the corresponding application window. In this case, the terminal window should bring in front (focus)

**Platform information:**
elementary OS 5.1.7 Hera. wingpanel-indicator-notifications (2.1.4)

**Comment by danrabbit** [comment] 2021-02-16 16:59
Hey, thanks for your issue report. In the future, it would be helpful to please follow the issue reporting template.

What version of elementary OS are you using to reproduce this issue? I am unable to reproduce on elementary OS 6

**Comment by shantanu-csedu** [comment] 2021-02-18 05:47
> Hey, thanks for your issue report. In the future, it would be helpful to please follow the issue reporting template.
> 
> What version of elementary OS are you using to reproduce this issue? I am unable to reproduce on elementary OS 6

Sorry for the incomplete information. OS version: elementary OS 5.1.7 Hera (up to date)

**Comment by KarkanAlzwayed** [comment] 2021-05-20 15:51
This also happens on EOS 6 beta. Nothing happens when I click on a notification from the missed notifications drop down menu.

**Comment by lorencinibrdev** [comment] 2021-09-18 05:55
Can't reproduce on a fully updated Odin install. Terminal comes up properly when clicked on missed notification.

Is this still an issue?

**Comment by danirabbit** [comment] 2023-08-29 22:32
This should be fully addressed by #263

**Closed by danirabbit** 2023-08-29 22:32 UTC
Labels: Status: Incomplete
